#!/usr/bin/env bash

# This is all from lf wiki

file=$1
w=$2
h=$3
x=$4
y=$5

if [[ "$( file -Lb --mime-type "$file")" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
    exit 1
elif [[ "$mimetype" =~ ^text ]]; then
    cat "$file"
    exit 0
fi

pistol "$file"
