#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "dark.css" ]; then
    SWITCHTO="-dark"
fi

#set the waybar theme
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/wofi/style/style$SWITCHTO.css ~/.config/wofi/style.css

#set the xfce theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
xfconf-query -c xsettings -p /Net/IconThemeName -s "elementary"
xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "elementary"

#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"
gsettings set org.gnome.desktop.interface icon-theme "elementary"
gsettings set org.gnome.desktop.interface cursor-theme "elementary"

#change the background image and be cool about it ;)
swww img ~/.config/hypr/lakeside$SWITCHTO.png --transition-fps 60 --transition-type wipe --transition-duration 2

#restart the waybar
killall -SIGUSR2 waybar
